services:
  stt:
    environment:
      # Override the device to be cuda
      - STT_DEVICE=cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
