#!/usr/bin/env bash
set -e

# Detect Python command (python3 on Unix, python on Windows)
if command -v python3 &> /dev/null; then
    PYTHON_CMD="python3"
elif command -v python &> /dev/null; then
    PYTHON_CMD="python"
else
    echo "❌ Error: Python not found. Please install Python."
    exit 1
fi

# Setup directories
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Resolve ".." to a clean absolute path
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ARTIFACTS_DIR="$PROJECT_ROOT/coverage-report"

# Cleanup previous run
rm -rf "$ARTIFACTS_DIR"
mkdir -p "$ARTIFACTS_DIR"

echo "=========================================="
echo "  TranslatAR Global Coverage Generation"
echo "=========================================="

# --- 1. Python Services ---
PYTHON_SERVICES=("backend" "stt-service" "translation-service" "summarization-service" "advice_service")

for service in "${PYTHON_SERVICES[@]}"; do
    echo ""
    echo "📊 Running coverage for: $service"

    if [ -d "$PROJECT_ROOT/$service" ]; then
        cd "$PROJECT_ROOT/$service"

        # Ensure dependencies exist (in case make clean was run)
        poetry install --quiet > /dev/null 2>&1 || true

        # Run pytest with coverage flags
        poetry run pytest --cov=. --cov-report=html:htmlcov --cov-report=json:coverage.json || true

        # Move artifacts to global folder
        if [ -d "htmlcov" ]; then
            mkdir -p "$ARTIFACTS_DIR/$service"
            cp -r htmlcov/* "$ARTIFACTS_DIR/$service/"
            cp coverage.json "$ARTIFACTS_DIR/$service/" 2>/dev/null || true
        else
            echo "⚠️  No coverage report generated for $service"
        fi
    else
        echo "⚠️  Directory $service not found, skipping..."
    fi
done

# --- 2. Web Portal ---
echo ""
echo "📊 Running coverage for: Web Portal"
if [ -d "$PROJECT_ROOT/web-portal" ]; then
    cd "$PROJECT_ROOT/web-portal"

    # Ensure node_modules exists and has vital dependencies
    if [ ! -d "node_modules" ] || [ ! -d "node_modules/vite" ]; then
        echo "📦 Installing Node dependencies (this may take a moment)..."
        npm install --silent --no-progress
    fi

    # Run vitest with coverage
    npm exec vitest -- run --coverage.enabled --coverage.reporter=html --coverage.reporter=json-summary || true

    # Move artifacts
    if [ -d "coverage" ]; then
        mkdir -p "$ARTIFACTS_DIR/web-portal"
        if [ -d "coverage/html" ]; then
             cp -r coverage/html/* "$ARTIFACTS_DIR/web-portal/"
        else
             cp -r coverage/* "$ARTIFACTS_DIR/web-portal/" 2>/dev/null || true
        fi
        if [ -f "coverage/coverage-summary.json" ]; then
            cp coverage/coverage-summary.json "$ARTIFACTS_DIR/web-portal/"
        fi
    else
        echo "⚠️  No coverage report generated for web-portal"
    fi
fi

# --- 3. Unity ---
echo ""
echo "📊 Running coverage for: Unity"

# Check for Unity availability
OS_NAME=$(uname -s | tr '[:upper:]' '[:lower:]')
UNITY_AVAILABLE=false

if [[ "$OS_NAME" == "darwin" ]]; then
    # Quick check for standard Unity Hub path
    if ls -1d /Applications/Unity/Hub/Editor/*/Unity.app/Contents/MacOS/Unity 2>/dev/null | head -n1 > /dev/null; then
        UNITY_AVAILABLE=true
    fi
elif [[ "$OS_NAME" == mingw* || "$OS_NAME" == cygwin* || "$OS_NAME" == msys* ]]; then
    UNITY_AVAILABLE=true
elif [[ "$OS_NAME" == "linux" ]] && [ -f "/proc/version" ] && grep -q -i "microsoft" /proc/version; then
    UNITY_AVAILABLE=true
fi

if [ "$UNITY_AVAILABLE" = true ]; then
    cd "$PROJECT_ROOT"

    if [ -f "$SCRIPT_DIR/run_unity_coverage.sh" ]; then
        "$SCRIPT_DIR/run_unity_coverage.sh" || true

        UNITY_COVERAGE_DIR="$PROJECT_ROOT/unity/CodeCoverage"
        UNITY_REPORT_DIR="$UNITY_COVERAGE_DIR/Report"
        UNITY_OPENCOV_DIR="$UNITY_COVERAGE_DIR/unity-opencov"

        mkdir -p "$ARTIFACTS_DIR/unity"

        # Try Summary.json first (if HTML report was generated by Unity)
        if [ -f "$UNITY_REPORT_DIR/Summary.json" ]; then
            echo "📊 Found Unity HTML report, copying..."
            cp -r "$UNITY_REPORT_DIR/"* "$ARTIFACTS_DIR/unity/" 2>/dev/null || true
            
            # Unity generates index.htm, but dashboard expects index.html
            if [ -f "$ARTIFACTS_DIR/unity/index.htm" ] && [ ! -f "$ARTIFACTS_DIR/unity/index.html" ]; then
                cp "$ARTIFACTS_DIR/unity/index.htm" "$ARTIFACTS_DIR/unity/index.html"
            fi

            # Convert Unity Summary.json to dashboard-friendly format
            $PYTHON_CMD - "$UNITY_REPORT_DIR/Summary.json" "$ARTIFACTS_DIR/unity/coverage.json" << 'PYTHON_CONVERT'
import json
import sys

try:
    with open(sys.argv[1]) as f:
        data = json.load(f)

    summary = data.get("summary", {})
    output = {
        "unity_format": True,
        "totals": {
            "covered_lines": summary.get("coveredlines", 0),
            "num_statements": summary.get("coverablelines", 0),
            "percent_covered": summary.get("linecoverage", 0)
        }
    }

    with open(sys.argv[2], "w") as f:
        json.dump(output, f, indent=2)
except Exception as e:
    print(f"Error converting Unity coverage: {e}")
PYTHON_CONVERT
            echo "✅ Unity coverage collected from Summary.json"

        # Fallback: Parse OpenCover XML files directly
        elif [ -d "$UNITY_OPENCOV_DIR" ]; then
            echo "📄 Parsing Unity OpenCover XML files..."

            $PYTHON_CMD - "$UNITY_OPENCOV_DIR" "$ARTIFACTS_DIR/unity/coverage.json" << 'PYTHON_PARSE_XML'
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

def parse_opencover_xml(xml_path):
    """Parse an OpenCover XML file and return coverage stats."""
    try:
        tree = ET.parse(xml_path)
        root = tree.getroot()
        summary = root.find('Summary')
        if summary is not None:
            return {
                'num_seq': int(summary.get('numSequencePoints', 0)),
                'visited_seq': int(summary.get('visitedSequencePoints', 0)),
                'pct': float(summary.get('sequenceCoverage', 0))
            }
    except Exception as e:
        print(f"  Warning: Could not parse {xml_path}: {e}")
    return {'num_seq': 0, 'visited_seq': 0, 'pct': 0}

try:
    opencov_dir = sys.argv[1]
    output_path = sys.argv[2]

    best_result = None
    best_pct = -1

    # Find the XML file with the highest coverage percentage
    # (EditMode and PlayMode test the same code, so we take the best result)
    for xml_file in Path(opencov_dir).rglob('*.xml'):
        stats = parse_opencover_xml(xml_file)
        if stats['pct'] > best_pct:
            best_pct = stats['pct']
            best_result = stats
            best_file = xml_file

    if best_result and best_result['num_seq'] > 0:
        total_lines = best_result['num_seq']
        covered_lines = best_result['visited_seq']
        pct = round(best_result['pct'], 2)
        print(f"  Best coverage from: {best_file.parent.name}/{best_file.name}")
    else:
        total_lines = 0
        covered_lines = 0
        pct = 0

    output = {
        "unity_format": True,
        "totals": {
            "covered_lines": covered_lines,
            "num_statements": total_lines,
            "percent_covered": pct
        }
    }

    with open(output_path, "w") as f:
        json.dump(output, f, indent=2)

    print(f"  Unity Coverage: {pct}% ({covered_lines}/{total_lines} lines)")

except Exception as e:
    print(f"Error parsing Unity OpenCover XML: {e}")
    sys.exit(1)
PYTHON_PARSE_XML

            # Generate detailed HTML report from OpenCover XML
            $PYTHON_CMD - "$UNITY_OPENCOV_DIR" "$ARTIFACTS_DIR/unity/index.html" << 'PYTHON_HTML_REPORT'
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from collections import defaultdict

def get_color(pct):
    if pct >= 80: return "#4a0"
    if pct >= 50: return "#ea0"
    return "#c00"

def get_bg_color(pct):
    if pct >= 80: return "#e6ffe6"
    if pct >= 50: return "#ffffcc"
    return "#ffe6e6"

def parse_opencover_detailed(xml_path):
    """Parse OpenCover XML and extract per-file coverage data."""
    files_data = {}
    try:
        tree = ET.parse(xml_path)
        root = tree.getroot()
        
        for module in root.findall('.//Module'):
            # Build file uid -> path mapping
            file_map = {}
            for f in module.findall('.//File'):
                file_map[f.get('uid')] = f.get('fullPath', 'Unknown')
            
            # Collect coverage per file
            for cls in module.findall('.//Class'):
                for method in cls.findall('.//Method'):
                    for seq_point in method.findall('.//SequencePoint'):
                        file_id = seq_point.get('fileid')
                        if file_id and file_id in file_map:
                            file_path = file_map[file_id]
                            if file_path not in files_data:
                                files_data[file_path] = {'total': 0, 'covered': 0}
                            files_data[file_path]['total'] += 1
                            if int(seq_point.get('vc', '0')) > 0:
                                files_data[file_path]['covered'] += 1
    except Exception as e:
        print(f"Warning: {e}")
    return files_data

try:
    opencov_dir = sys.argv[1]
    output_path = sys.argv[2]
    
    # Find the best XML file (highest coverage)
    best_file = None
    best_pct = -1
    
    for xml_file in Path(opencov_dir).rglob('*.xml'):
        try:
            tree = ET.parse(xml_file)
            root = tree.getroot()
            summary = root.find('Summary')
            if summary is not None:
                pct = float(summary.get('sequenceCoverage', 0))
                if pct > best_pct:
                    best_pct = pct
                    best_file = xml_file
        except:
            pass
    
    if not best_file:
        raise Exception("No valid XML files found")
    
    # Parse detailed coverage from best file
    files_data = parse_opencover_detailed(best_file)
    
    # Calculate totals
    total_lines = sum(f['total'] for f in files_data.values())
    covered_lines = sum(f['covered'] for f in files_data.values())
    total_pct = round((covered_lines / total_lines * 100), 2) if total_lines > 0 else 0
    
    # Group files by directory
    grouped = defaultdict(list)
    for file_path, data in files_data.items():
        # Extract relative path from Assets/Scripts
        if 'Assets/Scripts' in file_path:
            rel_path = file_path.split('Assets/Scripts/')[-1]
        else:
            rel_path = Path(file_path).name
        
        pct = round((data['covered'] / data['total'] * 100), 2) if data['total'] > 0 else 0
        
        # Get directory for grouping
        parts = rel_path.replace('\\', '/').split('/')
        if len(parts) > 1:
            group = parts[0]
        else:
            group = ''
        
        grouped[group].append({
            'name': rel_path,
            'total': data['total'],
            'covered': data['covered'],
            'pct': pct
        })
    
    # Sort files within each group
    for group in grouped:
        grouped[group].sort(key=lambda x: x['name'])
    
    # Generate HTML
    rows_html = ""
    for group in sorted(grouped.keys()):
        files = grouped[group]
        for f in files:
            bar_color = get_color(f['pct'])
            bg_color = get_bg_color(f['pct'])
            rows_html += f'''
            <tr style="background: {bg_color};">
                <td class="file-name">{f['name']}</td>
                <td class="metric">
                    <div class="progress-bar">
                        <div class="progress-fill" style="width: {f['pct']}%; background: {bar_color};"></div>
                    </div>
                    <span class="pct">{f['pct']}%</span>
                </td>
                <td class="metric-num">{f['covered']}/{f['total']}</td>
            </tr>'''
    
    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unity Code Coverage Report</title>
    <style>
        * {{ box-sizing: border-box; }}
        body {{ 
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            margin: 0; padding: 20px; background: #f4f4f4; color: #333;
        }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        
        .header {{
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            color: white; padding: 30px; border-radius: 8px 8px 0 0;
            display: flex; justify-content: space-between; align-items: center;
        }}
        .header h1 {{ margin: 0; font-size: 1.5rem; }}
        .header-stats {{ text-align: right; }}
        .header-pct {{ font-size: 2.5rem; font-weight: bold; }}
        .header-detail {{ opacity: 0.8; font-size: 0.9rem; }}
        
        .summary {{
            background: white; padding: 20px 30px; border-bottom: 1px solid #e0e0e0;
            display: flex; gap: 40px;
        }}
        .summary-item {{ text-align: center; }}
        .summary-label {{ font-size: 0.75rem; text-transform: uppercase; color: #666; letter-spacing: 0.05em; }}
        .summary-value {{ font-size: 1.5rem; font-weight: bold; margin-top: 4px; }}
        
        .content {{ background: white; border-radius: 0 0 8px 8px; overflow: hidden; }}
        
        table {{ width: 100%; border-collapse: collapse; }}
        th {{ 
            background: #f8f8f8; padding: 12px 16px; text-align: left;
            font-size: 0.75rem; text-transform: uppercase; color: #666;
            letter-spacing: 0.05em; border-bottom: 2px solid #e0e0e0;
        }}
        td {{ padding: 10px 16px; border-bottom: 1px solid #eee; }}
        
        .file-name {{ font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace; font-size: 0.85rem; }}
        .metric {{ width: 200px; }}
        .metric-num {{ width: 100px; text-align: right; font-family: monospace; color: #666; }}
        
        .progress-bar {{
            background: #e0e0e0; height: 10px; border-radius: 5px;
            overflow: hidden; display: inline-block; width: 120px;
            vertical-align: middle; margin-right: 10px;
        }}
        .progress-fill {{ height: 100%; border-radius: 5px; }}
        .pct {{ font-weight: 600; font-size: 0.85rem; }}
        
        tr:hover {{ filter: brightness(0.97); }}
        
        .back-link {{
            display: inline-block; margin-bottom: 15px; color: #0066cc;
            text-decoration: none; font-size: 0.9rem;
        }}
        .back-link:hover {{ text-decoration: underline; }}
    </style>
</head>
<body>
    <div class="container">
        <a href="../index.html" class="back-link">← Back to Dashboard</a>
        
        <div class="header">
            <div>
                <h1>Unity (C#) Code Coverage</h1>
                <div style="opacity: 0.7; margin-top: 5px; font-size: 0.9rem;">
                    GameRuntime &amp; LanguageUI Assemblies
                </div>
            </div>
            <div class="header-stats">
                <div class="header-pct" style="color: {get_color(total_pct)}">{total_pct}%</div>
                <div class="header-detail">{covered_lines} / {total_lines} lines covered</div>
            </div>
        </div>
        
        <div class="summary">
            <div class="summary-item">
                <div class="summary-label">Files</div>
                <div class="summary-value">{len(files_data)}</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Lines</div>
                <div class="summary-value">{total_lines}</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Covered</div>
                <div class="summary-value" style="color: {get_color(total_pct)}">{covered_lines}</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Coverage</div>
                <div class="summary-value" style="color: {get_color(total_pct)}">{total_pct}%</div>
            </div>
        </div>
        
        <div class="content">
            <table>
                <thead>
                    <tr>
                        <th>File</th>
                        <th>Coverage</th>
                        <th style="text-align: right;">Lines</th>
                    </tr>
                </thead>
                <tbody>
                    {rows_html}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>'''
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)
    
    print(f"  Generated HTML report with {len(files_data)} files")

except Exception as e:
    print(f"Error generating HTML report: {e}")
    # Fallback to simple HTML
    html = f'''<!DOCTYPE html>
<html><head><title>Unity Coverage</title></head>
<body style="font-family: sans-serif; padding: 40px;">
<h1>Unity Code Coverage</h1>
<p>Error generating detailed report: {e}</p>
<p>Raw XML files at: <code>unity/CodeCoverage/unity-opencov/</code></p>
</body></html>'''
    with open(output_path, 'w') as f:
        f.write(html)
PYTHON_HTML_REPORT
            echo "✅ Unity coverage collected from OpenCover XML"
        else
            echo "⚠️  No Unity coverage data found"
            rmdir "$ARTIFACTS_DIR/unity" 2>/dev/null || true
        fi
    else
        echo "⚠️  run_unity_coverage.sh not found, skipping Unity"
    fi
else
    echo "⚠️  Unity not available on this platform/machine, skipping..."
fi

# --- 4. Generate Dashboard ---
echo ""
echo "📈 Generating Dashboard..."
if [ -f "$SCRIPT_DIR/generate_dashboard.py" ]; then
    $PYTHON_CMD "$SCRIPT_DIR/generate_dashboard.py" "$ARTIFACTS_DIR"
else
    echo "❌ Error: scripts/generate_dashboard.py not found."
    exit 1
fi

# --- 5. Open Report ---
INDEX_PATH="$ARTIFACTS_DIR/index.html"
echo ""

if [ -f "$INDEX_PATH" ]; then
    echo "✅ Report ready at: $INDEX_PATH"

    case "$(uname -s)" in
       Darwin*) open "$INDEX_PATH" ;;
       Linux*)  xdg-open "$INDEX_PATH" 2>/dev/null || echo "Open '$INDEX_PATH' in your browser." ;;
       CYGWIN*|MINGW*|MSYS*) start "$INDEX_PATH" ;;
       *) echo "Open '$INDEX_PATH' in your browser to view." ;;
    esac
else
    echo "❌ Report generation failed (index.html missing)."
    exit 1
fi
